# Generated by Django 4.1.7 on 2023-03-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_user_mixzer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixzer',
            name='college',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
