# Generated by Django 4.1.7 on 2023-04-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_mixzer_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixzer',
            name='phone_number',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mixzer',
            name='college',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
