# Generated by Django 4.1.7 on 2023-04-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_jobpoints_jobpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='locations',
        ),
    ]
