# Generated by Django 4.1.7 on 2023-04-01 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_mixzer_phone_number_alter_mixzer_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixzer',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mixzer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=250)),
                ('reviewee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to='main_app.mixzer')),
                ('reviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='main_app.mixzer')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=250)),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='main_app.mixzer')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='main_app.mixzer')),
            ],
        ),
        migrations.CreateModel(
            name='Job_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('job_description', models.TextField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('job_type', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
                ('schedule', models.CharField(max_length=250)),
                ('students', models.ManyToManyField(to='main_app.mixzer')),
            ],
        ),
    ]
