# Generated by Django 4.1.7 on 2023-04-03 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_mixzer_location_alter_mixzer_phone_number_and_more'),
        ('main_app', '0007_message_created_on_review_created_on'),
    ]

    operations = [
    ]
