# Generated by Django 4.1.7 on 2023-04-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_message_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job_post',
            name='students',
        ),
        migrations.AddField(
            model_name='job_post',
            name='applicants',
            field=models.ManyToManyField(related_name='applicants', to='main_app.mixzer'),
        ),
        migrations.AddField(
            model_name='job_post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='main_app.mixzer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_post',
            name='candidates',
            field=models.ManyToManyField(related_name='candidates', to='main_app.mixzer'),
        ),
    ]
