# Generated by Django 4.1.7 on 2023-04-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_message_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_post',
            name='candidates',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
