# Generated by Django 4.1.7 on 2023-04-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_20230403_1720'),
        ('main_app', '0011_job_post_candidates'),
        ('main_app', '0011_remove_job_post_location_remove_job_post_students_and_more'),
    ]

    operations = [
    ]
