# Generated by Django 4.1.7 on 2023-04-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_merge_20230404_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_post',
            name='candidates',
        ),
        migrations.AddField(
            model_name='job_post',
            name='candidates',
            field=models.ManyToManyField(related_name='candidates', to='main_app.mixzer'),
        ),
    ]
